### ISSUE TITLE
validate_type -> convert_to_type

### ISSUE THREAD

**Issue by ilyash** [Andarius/piou#2]
Hi!

I suggest renaming the function. It converts to the given type. In "validate" I would expect either boolean result or no result / exception.

https://github.com/Andarius/piou/blob/fedc4514c0c74059bb5a5dcf69bb275448999726/piou/utils.py#L16

**Comment by Andarius** [comment]
Hey @ilyash, indeed, you are right, I'll make the change :)

**Comment by Andarius** [comment]
Done in 0.2.1
